### ISSUE TITLE
Live+Beta with one command?

### ISSUE THREAD

**Issue by AndrewSB** [Karim-Mohamed-Mousa/fastlane-plugin-instabug-official#3]
I have 2 apps in instabug, one for TestFlight, the other for the App Store. I was planning on just uploading my DYSMs to both apps when I release for either. My thought is it's harmless to upload a DYSM for a build that doesn't exist, since Instabug won't use it

```ruby
    download_dysm(...)
    instabug_official(
      api_token: instabug_beta_application_id
    )
    instabug_official(
      api_token: instabug_beta_application_id
    )
    clean_build_artifacts
```

It looks like running instabug_official deletes the DYSM, so the first call succeeds, the second fails with

`[16:04:23]: Fastlane dSYMs file is not found! make sure you're using Fastlane action [download_dsyms] to download your dSYMs from App Store Connect`

1. Is there some way to upload my DYSM to both apps in one command?
2. If not, how should I fix this? Do we need to patch this command to not delete the DYSMs after uploading? I'd rather have that happen than me passing through whether I'm uploading to TestFlight or the App Store, and picking which `api_token` to use based on that

**Comment by Kmohamed** [comment]
Hi @AndrewSB,
In order to understand you well. I think the TestFlight build is the same build as the AppStore build. So, Why do you need to upload it again?
Note: If you upload the DSYMs on the beat token and you got a crash on the live one it will be symbolicated as long as the UUID is matched.

**Comment by AndrewSB** [comment]
Got it. I can illustrate better with an example of a set of deployments:

1.3 (1) -> TF
1.3 (2) -> TF
1.3 (3) -> TF
1.3 (3) -> App Store
1.3 (4) -> TF
1.3.1 (1) -> TF
1.3.1 (1) -> App Store

So if I understand you correctly, I can simply upload DYSMs to the beta api_key, and crashes will be symbolicated for either build, assuming the hashes match.
I was under the assumption that the two `api_key`s wouldn't leak data between them, but from your explanation it sounds like they do (which makes our deployments a lot easier to manage)

If what I've said sounds right, this can be closed, thanks!

**Comment by Kmohamed** [comment]
Yes, Exactly 👌
Also, please tell me if anything go wrong.
